# Generated by Django 3.2.4 on 2022-06-24 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsads',
            name='formId',
            field=models.IntegerField(blank=True, db_column='form_id', null=True, verbose_name='Form Id'),
        ),
        migrations.AlterField(
            model_name='logleads',
            name='adsId',
            field=models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheetsads', to='sheets.sheetsads'),
        ),
        migrations.CreateModel(
            name='ColumnAds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('columnAds', models.CharField(blank=True, db_column='column_ads', max_length=1000, null=True, verbose_name='column Ads')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('adsId', models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets_ads', to='sheets.sheetsads')),
            ],
            options={
                'db_table': 'tbl_column_ads',
            },
        ),
    ]
