# Generated by Django 3.2.4 on 2022-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20220624_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsads',
            name='channelName',
            field=models.CharField(blank=True, db_column='channel_name', max_length=1000, null=True, verbose_name='Channel Name'),
        ),
        migrations.AlterField(
            model_name='sheetsads',
            name='status',
            field=models.CharField(blank=True, db_column='status', default='running', max_length=1000, null=True, verbose_name='Status'),
        ),
    ]
