# Generated by Django 3.2.4 on 2022-07-04 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_sheetsads_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('email', models.CharField(blank=True, db_column='email', max_length=1000, null=True, verbose_name='Email')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('status', models.CharField(blank=True, db_column='status', default='not connected', max_length=1000, null=True, verbose_name='Status')),
                ('totalIntegration', models.IntegerField(blank=True, db_column='total_integration', null=True, verbose_name='total Integration')),
            ],
            options={
                'db_table': 'tbl_sheets_accounts',
            },
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='adsAccId',
            field=models.ForeignKey(blank=True, db_column='adsAccId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adsAccId', to='sheets.sheetsaccounts'),
        ),
    ]
