# Generated by Django 3.2.4 on 2022-07-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_auto_20220704_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetsaccounts',
            name='totalIntegration',
            field=models.IntegerField(blank=True, db_column='total_integration', default=0, null=True, verbose_name='total Integration'),
        ),
    ]
