# Generated by Django 3.2.4 on 2022-07-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_sheetsaccounts_tooken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetsaccounts',
            old_name='tooken',
            new_name='token',
        ),
    ]
