# Generated by Django 3.2.4 on 2022-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0009_rename_tooken_sheetsaccounts_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsaccounts',
            name='refresh_token',
            field=models.CharField(blank=True, db_column='refresh_token', max_length=1000, null=True, verbose_name='Refresh Token'),
        ),
    ]
