# Generated by Django 3.2.4 on 2022-07-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_alter_sheetsads_channelid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetsads',
            name='account_sheets',
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='account_sheet',
            field=models.CharField(blank=True, db_column='account_sheet', max_length=1000, null=True, verbose_name='Account sheets'),
        ),
    ]
