# Generated by Django 3.2.4 on 2022-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_alter_sheetsaccounts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsads',
            name='campaignId',
            field=models.IntegerField(blank=True, db_column='campaign_id', null=True, verbose_name='Campaign Id'),
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='campaignName',
            field=models.CharField(blank=True, db_column='campaign_name', max_length=1000, null=True, verbose_name='Campaign Name'),
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='projectId',
            field=models.IntegerField(blank=True, db_column='project_id', null=True, verbose_name='project Id'),
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='projectName',
            field=models.CharField(blank=True, db_column='project_name', max_length=1000, null=True, verbose_name='project Name'),
        ),
    ]
