# Generated by Django 3.2.4 on 2022-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_auto_20220725_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsads',
            name='end_date',
            field=models.DateTimeField(blank=True, db_column='end_date', null=True, verbose_name='End date'),
        ),
    ]
