# Generated by Django 3.2.4 on 2022-12-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_sheetsads_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetsads',
            name='head',
            field=models.IntegerField(blank=True, db_column='head_column', default=0, null=True, verbose_name='Head Column'),
        ),
    ]
