# Generated by Django 3.2.4 on 2023-02-22 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_sheetsads_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=1000, null=True, verbose_name='Name')),
                ('columnAds', models.CharField(blank=True, db_column='column_ads', max_length=1000, null=True, verbose_name='column Ads')),
                ('text', models.CharField(blank=True, db_column='text', max_length=1000, null=True, verbose_name='text')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('adsId', models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheetsid', to='sheets.sheetsads')),
            ],
            options={
                'db_table': 'tbl_column_text',
            },
        ),
    ]
