# Generated by Django 3.2.4 on 2023-02-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0018_columntext'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnads',
            name='text',
            field=models.CharField(blank=True, db_column='text', max_length=1000, null=True, verbose_name='text'),
        ),
        migrations.DeleteModel(
            name='ColumnText',
        ),
    ]
