# Generated by Django 3.2.4 on 2023-02-25 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_auto_20230225_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='logleads',
            name='isFilter',
            field=models.BooleanField(db_column='is_filter', default=False, verbose_name='is filter'),
        ),
        migrations.AlterField(
            model_name='columnads',
            name='adsId',
            field=models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets_id', to='sheets.sheetsads'),
        ),
        migrations.AlterField(
            model_name='columnads',
            name='columnAds',
            field=models.CharField(blank=True, db_column='column_ads', max_length=1000, null=True, verbose_name='column Ads name'),
        ),
        migrations.CreateModel(
            name='FilterSetup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('columnAds', models.CharField(blank=True, db_column='column_ads', max_length=1000, null=True, verbose_name='Column Ads')),
                ('text', models.CharField(blank=True, db_column='text', max_length=1000, null=True, verbose_name='text')),
                ('createdAt', models.DateTimeField(blank=True, db_column='createdAt', default=django.utils.timezone.now, null=True, verbose_name='Created At')),
                ('createdBy', models.IntegerField(blank=True, db_column='createdBy', null=True, verbose_name='Created By')),
                ('modifiedAt', models.DateTimeField(blank=True, db_column='modifiedAt', null=True, verbose_name='Modified At')),
                ('modifiedBy', models.IntegerField(blank=True, db_column='modifiedBy', null=True, verbose_name='Modified By')),
                ('accountId', models.IntegerField(blank=True, db_column='accountId', null=True, verbose_name='Account Id')),
                ('adsId', models.ForeignKey(blank=True, db_column='ads_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets_ads', to='sheets.sheetsads')),
            ],
            options={
                'db_table': 'tbl_filter_setuo',
            },
        ),
    ]
