# Generated by Django 3.2.4 on 2023-02-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0020_auto_20230225_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersetup',
            name='filter',
            field=models.CharField(blank=True, db_column='filter', max_length=1000, null=True, verbose_name='Filter'),
        ),
    ]
