# Generated by Django 3.2.4 on 2023-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0021_filtersetup_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetsads',
            name='process',
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='isFilter',
            field=models.BooleanField(db_column='is_filter', default=False, verbose_name='is filter'),
        ),
    ]
