# Generated by Django 3.2.4 on 2023-06-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0025_auto_20230227_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='logleads',
            name='log',
            field=models.CharField(blank=True, db_column='log', max_length=1000, null=True, verbose_name='Log'),
        ),
        migrations.AddField(
            model_name='sheetsads',
            name='lastrow',
            field=models.CharField(blank=True, db_column='lastrow', max_length=1000, null=True, verbose_name='Laast Row'),
        ),
    ]
