# Generated by Django 3.2.4 on 2023-06-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0026_auto_20230605_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='logleads',
            name='adsName',
            field=models.CharField(blank=True, db_column='ads_name', max_length=1000, null=True, verbose_name='ads Name'),
        ),
        migrations.AddField(
            model_name='logleads',
            name='lead_email',
            field=models.CharField(blank=True, db_column='lead_email', max_length=1000, null=True, verbose_name='lead email'),
        ),
        migrations.AddField(
            model_name='logleads',
            name='lead_name',
            field=models.CharField(blank=True, db_column='lead_name', max_length=1000, null=True, verbose_name='lead name'),
        ),
        migrations.AddField(
            model_name='logleads',
            name='lead_notes',
            field=models.CharField(blank=True, db_column='lead_notes', max_length=1000, null=True, verbose_name='lead notes'),
        ),
    ]
